title: Michael Dayah - Lucent.Vision
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Michael Dayah
author-img: lucent-avatar.jpg
about-author: "\"Thinkers aren't limited by what they know, because they can always increase what they know. Rather they're limited by what puzzles them, because there's no way to become curious about something that doesn't puzzle you.\" ―Daniel Quinn"
social-twitter: Lucent
social-facebook: lucent
social-github: Lucent
social-linkedin: lucent
social-email: # add your Email address

# Comments
comments-reponame: Dayah/lucent.vision

# Tracker
analytics: UA-4174088-2

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 30
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package*.json", "yarn.lock", "LICENSE", "CNAME", "assets/"]
